### ISSUE TITLE
Joystick2 Issue

### ISSUE THREAD

**Issue by y0shimari0** [Ordinaryperson2/3DSController#11]
Trying to use the Joystick 1 and 2 ends up for joystick 1 working and joystick 2 not regestering at all.

**Comment by Ordinaryperson2** [comment]
Can't confirm, they work fine for me (even pressing both at the exact same time). Are you sure you've typed the settings correctly?
What specifically are you setting them on? (c stick? touch screen?)

**Comment by y0shimari0** [comment]
Heres my config file:
[3DSController.txt](https://github.com/Ordinaryperson2/3DSController/files/41234/3DSController.txt)

**Comment by Ordinaryperson2** [comment]
You don't have anything set to joystick 2?

**Comment by y0shimari0** [comment]
Sorry, wrong one:
[3DSController.txt](https://github.com/Ordinaryperson2/3DSController/files/41235/3DSController.txt)

**Comment by Ordinaryperson2** [comment]
Hm, ok. I don't see why that wouldn't work, but I don't remember whether I ever tested it (and there have been changed since if i have). I can take a look when i get home.

By the way, your ini isn't from the latest version which merged a lot of changes from RedInquisitive's fork. This does include changes to touch/joystick so maybe just updating will help you?

**Comment by y0shimari0** [comment]
Im currently using the .7.1 version.

**Comment by Ordinaryperson2** [comment]
Oh, yeah whoops i forgot i never actually released 0.7.2 because I wanted to include a .cia and basically I don't know how to do that :P

But yeah if you grab the latest .exe, .ini and .3dsx from the repo itself rather than releases you'll be on 0.7.2 and maybe it'll work? But I'm not really sure, I'm not home to test right now.

**Comment by y0shimari0** [comment]
Thanks, i'll try it right now.

**Comment by y0shimari0** [comment]
Because this issue is over 1 year old, im just closing it.
